### ISSUE TITLE
Deprecated authorization method

### ISSUE THREAD

**Issue by arielj** [fastruby/points#10]
**I received this email from GitHub, saying we have to use a different authorization method (Authorization HTTP header instead of the access_token query parameter that's being used now)**

Hello there!

On November 9th, 2020 at 02:32 (UTC) your application (Points Development) used an access token (with the User-Agent Faraday v0.15.4) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team

**Comment by bronzdoc** [comment]
@arielj I think this happened since last week I was developing in an old version of points, so when I logged in the deprecation warning was raised.

This was fixed in https://github.com/ombulabs/points/pull/68/files

![Screen Shot 2020-11-11 at 7 59 06 AM](https://user-images.githubusercontent.com/4595174/98820450-cc818f00-23f3-11eb-9ada-741cc7d6b36d.png)

**Comment by bronzdoc** [comment]
I will close this but if you still experiencing this issue with the current version of points I'm happy to re open it
