### ISSUE TITLE
Sign in is not working in Heroku review apps 

### ISSUE THREAD

**Issue by etagwerker** [fastruby/points#48]
**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

`main` 

**Expected behavior:**

I'd like review apps to let me sign in with my Github username (as it would in production) 

**Actual behavior:**

When trying to sign in I end up in the GitHub 404 page.

**Steps to reproduce:**

1. Step 1: Go to any review app
2. Step 2: Try to sign in

**Screenshots and Videos**

It will redirect to a URL that looks like this: https://github.com/login/oauth/authorize?client_id&redirect_uri=https%3A%2F%2Fpoints-fix-csv-import-e-z5ds36.herokuapp.com%2Fusers%2Fauth%2Fgithub%2Fcallback&response_type=code&scope=user%3Aemail&state=656a13668efdf41a985047c6798ae108eec02eaa124b0bc9

<img width="1362" alt="Screen Shot 2021-06-07 at 9 17 52 PM" src="https://user-images.githubusercontent.com/17584/121107866-b9427080-c7d6-11eb-9b97-5166a64513c0.png">

**Logs**

Include relevant log snippets or files here.

**I will abide by the [code of conduct](CODE_OF_CONDUCT.md)**

**Comment by buys-fran** [comment]
Working on this one

**Comment by buys-fran** [comment]
After lots of research and trying a few things. I have come to the conclusion that there are 3 ways to solve this problem.

1. Create a proxy server, so staging requests can Auth with the same URL production apps auth with.
Not ideal since code meant for staging is deployed to production.
2. Dynamically create a Github APP with the review apps URL as a redirect URL. 
This will require the user to visit the page to create a new app from a manifest. Also not ideal since staging code is deployed to production.
3. Add an alternative login method for staging.

Does anyone mind weighing in on these alrternatives?

**Comment by buys-fran** [comment]
Some links about the github api + creating an app with a manifest.
- https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-from-a-manifest
- https://docs.github.com/en/rest/reference/apps#create-a-github-app-from-a-manifest

**Comment by buys-fran** [comment]
Some twitter wisdom:
https://twitter.com/searls/status/1012343568072105984

**Comment by fbuys** [comment]
Thanks for the feedback @arielj from what I've seen on Twitter (I know who believes Twitter??), but it seems like option 3 is he simplest. 

And option 1 does seem the most robust, but it will also only work if this PR is merged: https://github.com/omniauth/omniauth/pull/1047

I would like to go with option 1, and when we really need to test OAuth then we can update the OAuth URL in Github.
