### ISSUE TITLE
Add ability to Filter/Search stories

### ISSUE THREAD

**Issue by fbuys** [fastruby/points#49]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

- [x] I checked the documentation and didn't find this feature
- [x] I checked to make sure that this feature has not already been requested

**Branch/Commit:**

`main`

**Describe the feature:**

Please include a detailed description of the feature you are requesting and any detail on it’s expected behavior.

> **As a estimator**
> **I would like to look (or filter) for stories by name**
> **And then I open a project type into a searchbox**
> **And I see stories related to the input text**

**Problem:**

Currently when a project grows it becomes harder and harder to find stories.
This could cause us to add duplicate stories when we cannot find an existing story.

**Mockups:**

TBD

**Resources:**

TBD 

**I will abide by the [code of conduct](CODE_OF_CONDUCT.md)**

**Comment by mateusdeap** [comment]
I wonder, wouldn't this be an elaboration of #7? I can take a look into this. Maybe we can add labels and allow the search to go over both labels and descriptions?

**Comment by buys-fran** [comment]
Sounds good, I think any search ability would be good to start with. Then we can expand to labels etc.

**Comment by mateusdeap** [comment]
So, I made a first implementation using [ransack](https://github.com/activerecord-hackery/ransack) (which I've used many times in the past and I really like it). However, I would like some comments on the UI/UX side of things

![image](https://user-images.githubusercontent.com/14188887/121590850-33f5d080-ca0f-11eb-9a34-8ce0688c61b2.png)

I wonder how could this be made to be less horrible? Also, is there a guide anywhere for our css styles or something?

**Comment by buys-fran** [comment]
Hey @mateusdeap, nice progress 👍

I think it can be slimmed down a bit, it is taking up quite a bit of vertical space at the moment.
I am not sure we need a search button, we could debounce keyDown and search as the user types perhaps?

Slimmed down ideas:
![image](https://user-images.githubusercontent.com/3785596/121683947-57c41f80-cabe-11eb-996a-3b8f01ce6f12.png)
![image](https://user-images.githubusercontent.com/3785596/121683975-61e61e00-cabe-11eb-9795-64311d62b9c9.png)

**Comment by mateusdeap** [comment]
@buys-fran checkout the `feature/filter-stories` branch. It has what I worked on until now. I only have 2 comments for the time being:

- Tests are still missing. I intend to add them later
- Despite the fact that it works pretty well, I believe, I think some further modifications will be needed, like extracting a template or some such, to be rendered using a `js.erb` file. The reason is that every form submission unfocuses the input field used to filter the stories. This means that after it updates the list, we need to click the input field again in order to change the search terms. It's somewhat annoying, in my opinion...
